/** Public assets generated by scripts/copy-maplibre-worker.mjs. */
export const MAP_WORKER_URL = "/maplibre/maplibre-gl-worker.mjs";

/** CARTO Positron vector style; no API key required. */
export const MAP_STYLE = "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json";
